<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HAAR0538" name="testrunner.TestRunner" tests="1" failures="0" timestamp="7 Sep 2021 20:08:53 GMT" time="29.849" errors="1">
  <testcase name="runScenario" time="29.849" classname="testrunner.TestRunner">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertFalse(Assert.java:39)
	at junit.framework.Assert.assertFalse(Assert.java:47)
	at stepdefinition.CAcceptpayment.val_accept_pay(CAcceptpayment.java:40)
	at ?.Validate Accept Payment page(file:///D:/PRODHATF/features/CheckinAsyst/Appointments/AcceptPayment.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testrunner.TestRunner -->
